[pytest]
minversion = 7.0
addopts = --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
log_cli = true
log_cli_level = INFO
markers =
    regression: full regression scenarios
    smoke: smoke test scenarios
